[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./App serve --env production --hostname 0.0.0.0 --port 8080"
healthcheckPath = "/v1/health"
healthcheckTimeout = 120

[environments.production.variables]
LOG_LEVEL = "notice"
